server:
  port: 36257

spring:
  datasource:
    url: ${db.url}
    driver-class-name: org.postgresql.Driver
    username: ${db.userName}
    password: ${db.password}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDB201Dialect
    show-sql: false

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO